# Generated by Django 2.0.6 on 2018-07-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opticclose', models.TextField(max_length=20000)),
                ('opticmos', models.TextField(max_length=20000)),
                ('sarclose', models.TextField(max_length=20000)),
                ('sarmos', models.TextField(max_length=20000)),
                ('seaice', models.TextField(max_length=20000)),
                ('icedrift', models.TextField(max_length=20000)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fram.Position')),
            ],
        ),
    ]
