# Generated by Django 2.0.6 on 2018-07-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fram', '0002_layers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Layers',
            new_name='Layer',
        ),
    ]
